---
destination_path: './data/outputs/main_output.json'
params:
  bioarxiv:
    paging: 2
    batches: 3
    parse: true
  arxiv:
    start: 0
    max_results: 3
    parse: true
  medline:
    max_results: 3
    start: 0
    parse: true
